name: Ensure API ARM Peer Dependency

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  peer-api-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Check API dependency semantics (stable)
        working-directory: packages
        run:   |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          arm64v8/node:14 \
          bash -exc 'apt-get update && apt-get -y install curl && \
          npm install -g lerna && \
          npm install semver && \
          lerna run peer-api-check'
